// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
  datasource: {
    // Migrations need Neon's *direct* (unpooled) connection — the pooled
    // PgBouncer endpoint doesn't support the DDL/advisory locks Migrate needs.
    // The app itself (src/lib/prisma.ts) uses the pooled DATABASE_URL instead.
    url: process.env["DIRECT_URL"] || process.env["DATABASE_URL"],
  },
});
