import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { prisma } from "@/lib/prisma";
import { getCurrentUser } from "@/lib/auth/session";
import { newId } from "@/lib/id";
import { notifyTenantBillCreated } from "@/lib/mail";

/** Bill types Admin can issue through the tenant-uploads-slip → Admin-approves flow.
 * Covers the move-in Outstanding (DEPOSIT/ADMIN_FEE/ACCESS_CARD/first RENTAL) as well as
 * the recurring monthly charges (RENTAL/UTILITIES/AC/DRYER/ELECTRIC). LATE_FEE is excluded
 * here — those are only ever auto-generated by the cron job, never hand-created. */
const BILL_TYPES = [
  "DEPOSIT",
  "UTILITIES",
  "RENTAL",
  "ADMIN_FEE",
  "ACCESS_CARD",
  "AC",
  "DRYER",
  "ELECTRIC",
  "OTHER",
] as const;

const createSchema = z.object({
  type: z.enum(BILL_TYPES),
  amountDue: z.coerce.number().positive(),
  dueDate: z.string().trim().min(1),
  periodMonth: z.string().trim().optional().default(""),
  notes: z.string().trim().optional().default(""),
});

/** Admin issues a bill (a Payment row with status PENDING) for the tenant to pay and upload
 * proof against — used for the recurring RENTAL/UTILITIES/AC/DRYER charges. */
export async function POST(
  req: NextRequest,
  { params }: { params: Promise<{ contractId: string }> }
) {
  const user = await getCurrentUser();
  if (!user || user.role !== "ADMIN") {
    return NextResponse.json({ success: false, message: "只有 Admin 可以开账单" }, { status: 403 });
  }
  const { contractId } = await params;
  const c = await prisma.contract.findUnique({
    where: { contractCode: contractId },
    include: { room: true, tenant: true },
  });
  if (!c) return NextResponse.json({ success: false, message: "找不到合同" }, { status: 404 });

  const parsed = createSchema.safeParse(await req.json().catch(() => null));
  if (!parsed.success) {
    return NextResponse.json({ success: false, message: "项目/金额/到期日一定要填" }, { status: 400 });
  }
  const d = parsed.data;

  if (d.type === "AC" && !c.room.hasAircon) {
    return NextResponse.json({ success: false, message: "这间房没有冷气，不能开冷气账单" }, { status: 400 });
  }

  const paymentCode = await newId("PY");
  await prisma.payment.create({
    data: {
      paymentCode,
      contractId: c.id,
      roomCode: c.room.roomCode,
      tenantId: c.tenantId,
      tenantName: c.tenantName,
      periodMonth: d.periodMonth,
      type: d.type,
      amountDue: d.amountDue,
      amountPaid: 0,
      dueDate: new Date(d.dueDate),
      status: "PENDING",
      recordedBy: user.name,
      notes: d.notes,
    },
  });

  if (c.tenant) {
    await notifyTenantBillCreated(
      c.tenant,
      {
        paymentCode,
        contractCode: c.contractCode,
        roomCode: c.room.roomCode,
        type: d.type,
        amountDue: d.amountDue,
        amountPaid: 0,
        dueDate: d.dueDate,
        periodMonth: d.periodMonth,
      },
      user.name
    );
  }

  return NextResponse.json({ success: true, message: `✅ 账单已开: ${d.type} RM${d.amountDue}` });
}
